eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: chen-user
#数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/quartz?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    username: mysql
mybatis:
  mapper-locations: classpath:mapper/*.xml
    #实体类的位置
  type-aliases-package: com.chen.user.entity
logging:
  level:
    com.chen.quartz.dao : debug