#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#server:
#  port: 8762
#spring:
#  application:
#    name: chen-quartz
##数据库连接
#  datasource:
#    url: jdbc:mysql://localhost:3306/quartz?serverTimezone=GMT&characterEncoding=utf-8
#    driver-class-name: com.mysql.jdbc.Driver
#    password: 123456
#    username: mysql
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#logging:
#  level:
#    com.chen.quartz.dao : debug